export enum NAVIGATION {
  BootstrapStackNav = 'BootstrapStackNav',
  HomeProfileNav = 'HomeProfileNav',
  MaintainaceAreaStackNav = 'MaintainaceAreaStackNav',
  ParkingAreaStackNav = 'ParkingAreaStackNav',
  ReserveCommonAreaStackNav = 'ReserveCommonAreaStackNav',
  SecurityApprovalsStackNav = 'SecurityApprovalsStackNav',
  HazardAreaStackNav = 'HazardAreaStackNav',
  AmbulanceAreaStackNav = 'AmbulanceAreaStackNav',
  SettingNav = 'SettingNav',
  EditProfileNav = 'EditProfileNav',
  PaymentDuesScreenNav = 'PaymentDuesScreenNav',
  ActiveBookingsNav = 'ActiveBookingsNav',
  CoResidentsNav = 'CoResidentsNav',
  HomeScreenNav = 'HomeScreenNav',
  AddCoResidentsNav = 'AddCoResidentsNav',
  TermsConditionsNav = 'TermsConditionsNav',
  ContactScreenNav = 'ContactScreenNav',
  FeedbackScreenNav = 'FeedbackScreenNav'
}

export enum MaintainanceAreasScreens {
  HomeProfile = 'HomeProfile',
  MaintainanceAreas = 'MaintainanceAreas',
  ParkingAreas = 'ParkingAreas',
  ReserveCommonAreas = 'ReserveCommonAreas',
  SecurityApprovals = 'SecurityApprovals',
  HazardAreas = 'HazardAreas',
  AmbulanceArea = 'AmbulanceArea',
  LogDetailsArea = 'LogDetailsArea',
  MaintainanceCardDetails = "MaintainanceCardDetails",
  MaintainanceListDetails = "MaintainanceListDetails",
  NotificationDetails = 'NotificationDetails',
  ReserveDetailsArea = 'ReserveDetailsArea',
  AddReserveParkingDetails = 'AddReserveParkingDetails',
  ReservedConfirmation = 'ReservedConfirmation',
  Setting = 'Setting',
  EditProfile = 'EditProfile',
  PaymentDuesScreen = 'PaymentDuesScreen',
  ActiveBookings = 'ActiveBookings',
  CoResidents = 'CoResidents',
  HomeScreen = 'HomeScreen',
  AddCoResidents = 'AddCoResidents',
  TermsConditions = 'TermsConditions',
  ContactScreen = 'ContactScreen',
  FeedbackScreen = 'FeedbackScreen',
}

export enum BootstrapNavigationScreens {
  Login = 'Login',
  VerifyOTP = 'VerifyOTP',
}