export const AuthActionTypes = {
    SEND_OTP_ACTION: 'SEND_OTP_ACTION',
    SEND_OTP_SUCCESS_ACTION: 'SEND_OTP_SUCCESS_ACTION',
    SEND_OTP_FAILURE_ACTION: 'SEND_OTP_FAILURE_ACTION',
    VERIFY_OTP_ACTION: 'VERIFY_OTP_ACTION',
    VERIFY_OTP_SUCCESS_ACTION: 'VERIFY_OTP_SUCCESS_ACTION',
    VERIFY_OTP_FAILURE_ACTION: 'VERIFY_OTP_FAILURE_ACTION',
};

export const ActionTypes ={
    FETCH_HOME_PROFILE_DATA: 'FETCH_HOME_PROFILE_DATA',
    FETCH_HOME_PROFILE_DATA_SUCCESS:'FETCH_HOME_PROFILE_DATA_SUCCESS',
    FETCH_HOME_PROFILE_DATA_FAILURE: 'FETCH_HOME_PROFILE_DATA_FAILURE',
    GENERATE_TOKEN: "GENERATE_TOKEN",
    GENERATE_TOKEN_SUCCESS: "GENERATE_TOKEN_SUCCESS",
    GENERATE_TOKEN_FAILURE: "GENERATE_TOKEN_FAILURE",
    FETCH_MAINTENANCE_DATA: 'FETCH_MAINTENANCE_DATA',
    FETCH_MAINTENANCE_DATA_SUCCESS: 'FETCH_MAINTENANCE_DATA_SUCCESS',
    FETCH_MAINTENANCE_DATA_FAILURE: 'FETCH_MAINTENANCE_DATA_FAILURE',
    FETCH_Amenity_Problem_DATA: 'FETCH_Amenity_Problem_DATA',
    FETCH_Amenity_Problem_DATA_SUCCESS: 'FETCH_Amenity_Problem_DATA_SUCCESS',
    FETCH_Amenity_Problem_DATA_FAILURE: 'FETCH_Amenity_Problem_DATA_FAILURE',
    GENERATE_ENTRY_ACTION: 'GENERATE_ENTRY_ACTION',
    GENERATE_ENTRY_SUCCESS: 'GENERATE_ENTRY_SUCCESS',
    GENERATE_ENTRY_FAILURE: 'GENERATE_ENTRY_FAILURE',
    FETCH_SECURITY_APPROVAL: 'FETCH_SECURITY_APPROVAL',
    FETCH_SECURITY_APPROVAL_SUCCESS: 'FETCH_SECURITY_APPROVAL_SUCCESS',
    FETCH_SECURITY_APPROVAL_FAILURE: 'FETCH_SECURITY_APPROVAL_FAILURE',
}