export const AuthActionTypes = {
    SEND_OTP_ACTION: 'SEND_OTP_ACTION',
    SEND_OTP_SUCCESS_ACTION: 'SEND_OTP_SUCCESS_ACTION',
    SEND_OTP_FAILURE_ACTION: 'SEND_OTP_FAILURE_ACTION',
    VERIFY_OTP_ACTION: 'VERIFY_OTP_ACTION',
    VERIFY_OTP_SUCCESS_ACTION: 'VERIFY_OTP_SUCCESS_ACTION',
    VERIFY_OTP_FAILURE_ACTION: 'VERIFY_OTP_FAILURE_ACTION',
};